
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver


  redis:
    database: 3
    host: localhost
    port: 6379
    password:
    timeout: 6000ms


  mybatis:
    executor-type: simple
    check-config-location: false
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.bean
    type-enums-package: com.example.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler


  cache:
    redis:
      time-to-live: 3600000ms


springbootTest:
  redis:
    open: true

  shiro:
    redis: true
    expireIn: 1800
    sessionTimeout: 1800000
    cookieTimeout: 2592000
    anonUrl: /css/**,/js/**,/fonts/**,/adminres/**,/img/**
    loginUrl: /login
    successUrl: /admin/index
    logoutUrl: /logout
    unauthorizedUrl: /error
    sessionIdName: hayek.session.id

server:
  port: 8080
