
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver


  redis:
    database: 3
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）


  mybatis:
     executor-type: simple  #指定mybatis的执行器
     check-config-location: false    #启动时检测xml文件是否存在（默认不检测）
     config-locations: classpath:mybatis/mybatis-config.xml
     mapper-locations: classpath:mapper/*.xml     #mapper 额外的xml指定的位置
     type-aliases-package: com.example.bean
     type-enums-package: com.example.enums       #枚举扫描路径
     configuration:       #枚举配置
       default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler    #默认将枚举的值保存到数据库中


  cache:
    redis:
      time-to-live: 3600000ms #过期时间，默认为永不过期，这里配置为过期时间 60分钟 60*60*1000



springbootTest:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
  shiro:
      redis: true # true表示shiro session存到redis里，需要开启redis，才会生效，集群环境下使用


server:   #tomcat服务器开启端口8080
    port: 8080
